version: '3.5'

services: 
  frontend:
    image: node:12-alpine
    container_name: frontend-miganado
    volumes: 
      - ./:/app:cached
    working_dir: /app
    networks: 
      - appan
    ports: 
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: sh -c "npm install && npm start"
    tty: true

networks: 
  appan: 
    external: true
    name: appan